### ISSUE TITLE
creating $VIN.json in weather cache

### ISSUE THREAD

**Issue by jonjis** [superwofy/CICPortal#1]
`$weather_data = file_get_contents` in main.php wont send `$VIN `header data which contains` BMW-VIN `to the get-weather.php 
`stream_context_create` might be helpful...

**Comment by superwofy** [comment]
Hello,

Thank you for the suggestion. Indeed you are right, get-weather.php does not have access to the headers when called by file_get_contents.
I addressed the issue in the last commit by assigning $VIN with a GET parameter instead. This is the way it was meant to be originally but some copy-paste mistake introduced $_SERVER instead of $_GET.

Kind regards.
